#!/bin/bash

echo "Enter URL address:"
read address

echo "Select the number of page requests:"
read number

echo "Number of competitive requests:"
read requests

ab -n $number -c $requests -k -r -H "User-Agent: Google Bot" $address
